# Generated by Django 3.1.5 on 2021-01-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_advertiser',
            field=models.BooleanField(default=False),
        ),
    ]
